"""
Programmed by Jason Zutty
"""
import numpy as np
import csv
from io import StringIO

def get_base_data_fields():
    """
    This method returns the data fields in the base records file for THCIC files
    """
    base_data_fields = [ DataField('DISCHARGE', 6, np.str),
                         DataField('THCIC_ID', 6, np.str),
                         DataField('PROVIDER_NAME', 55, np.str),
                         DataField('FAC_TEACHING_IND', 1, np.str),
                         DataField('FAC_PSYCH_IND', 1, np.str),
                         DataField('FAC_REHAB_IND', 1, np.str),
                         DataField('FAC_ACUTE_CARE_IND', 1, np.str),
                         DataField('FAC_SNF_IND', 1, np.str),
                         DataField('FAC_LONG_TERM_AC_IND', 1, np.str),
                         DataField('FAC_OTHER_LTC_IND', 1, np.str),
                         DataField('FAC_PEDS_IND', 1, np.str),
                         DataField('SPEC_UNIT', 5, np.str),
                         DataField('SPEC_UNIT_1', 1, np.str),
                         DataField('SPEC_UNIT_2', 1, np.str),
                         DataField('SPEC_UNIT_3', 1, np.str),
                         DataField('SPEC_UNIT_4', 1, np.str),
                         DataField('SPEC_UNIT_5', 1, np.str),
                         DataField('ENCOUNTER_INDICATOR', 2, np.str),
                         DataField('SEX', 1, np.str),
                         DataField('TYPE_OF_ADMISSION', 1, np.str),
                         DataField('SOURCE_OF_ADMISSION', 1, np.str),
                         DataField('PAT_STATE', 2, np.str),
                         DataField('PAT_ZIP', 5, np.str),
                         DataField('PAT_COUNTRY', 2, np.str),   
                         DataField('COUNTY', 3, np.str),
                         DataField('PUBLIC_HEALTH_REGION', 2, np.str),
                         DataField('ADMIT_WEEKDAY', 1, np.str),
                         DataField('LENGTH_OF_STAY', 4, np.float),
                         DataField('PAT_AGE', 2, np.str),
                         DataField('PAT_STATUS', 2, np.str),
                         DataField('RACE', 1, np.str),
                         DataField('ETHNICITY', 1, np.str),
                         DataField('FIRST_PAYMENT_SRC', 2, np.str),
                         DataField('SECONDARY_PAYMENT_SRC', 2, np.str),
                         DataField('TYPE_OF_BILL', 3, np.str),
                         DataField('PRIVATE_AMOUNT', 12, np.float),
                         DataField('SEMI_PRIVATE_AMOUNT', 12, np.float),
                         DataField('WARD_AMOUNT', 12, np.float),
                         DataField('ICU_AMOUNT', 12, np.float),
                         DataField('CCU_AMOUNT', 12, np.float),
                         DataField('OTHER_AMOUNT', 12, np.float),
                         DataField('PHARM_AMOUNT', 12, np.float),
                         DataField('MEDSURG_AMOUNT', 12, np.float),
                         DataField('DME_AMOUNT', 12, np.float),
                         DataField('USED_DME_AMOUNT', 12, np.float),
                         DataField('PT_AMOUNT', 12, np.float),
                         DataField('OT_AMOUNT', 12, np.float),
                         DataField('SPEECH_AMOUNT', 12, np.float),
                         DataField('IT_AMOUNT', 12, np.float),
                         DataField('BLOOD_AMOUNT', 12, np.float),
                         DataField('BLOOD_ADMIN_AMOUNT', 12, np.float),
                         DataField('OR_AMOUNT', 12, np.float),
                         DataField('LITH_AMOUNT', 12, np.float),
                         DataField('CARD_AMOUNT', 12, np.float),
                         DataField('ANES_AMOUNT', 12, np.float),
                         DataField('LAB_AMOUNT', 12, np.float),
                         DataField('RAD_AMOUNT', 12, np.float),
                         DataField('MRI_AMOUNT', 12, np.float),
                         DataField('OP_AMOUNT', 12, np.float),
                         DataField('ER_AMOUNT', 12, np.float),
                         DataField('AMBULENCE_AMOUNT', 12, np.float),
                         DataField('PRO_FEE_AMOUNT', 12, np.float),
                         DataField('ORGAN_AMOUNT', 12, np.float),
                         DataField('ESRD_AMOUNT', 12, np.float),
                         DataField('CLINIC_AMOUNT', 12, np.float),
                         DataField('TOTAL_CHARGES', 12, np.float),
                         DataField('TOTAL_NON_COV_CHARGES', 12, np.float),
                         DataField('TOTAL_CHARGES_ACCOMM', 12, np.float),
                         DataField('TOTAL_NON_COV_CHARGES_ACCOMM', 12, np.float),
                         DataField('TOTAL_CHARGES_ANCIL', 12, np.float),
                         DataField('TOTAL_NON_COV_CHARGES_ANCIL', 12, np.float),
                         DataField('ADMITTING_DIAGNOSIS', 6, np.str),
                         DataField('PRINC_DIAG_CODE', 6, np.str),
                         DataField('OTH_DIAG_CODE_1', 6, np.str),
                         DataField('OTH_DIAG_CODE_2', 6, np.str),
                         DataField('OTH_DIAG_CODE_3', 6, np.str),
                         DataField('OTH_DIAG_CODE_4', 6, np.str),
                         DataField('OTH_DIAG_CODE_5', 6, np.str),
                         DataField('OTH_DIAG_CODE_6', 6, np.str),
                         DataField('OTH_DIAG_CODE_7', 6, np.str),
                         DataField('OTH_DIAG_CODE_8', 6, np.str),
                         DataField('OTH_DIAG_CODE_9', 6, np.str),
                         DataField('OTH_DIAG_CODE_10', 6, np.str),
                         DataField('OTH_DIAG_CODE_11', 6, np.str),
                         DataField('OTH_DIAG_CODE_12', 6, np.str),
                         DataField('OTH_DIAG_CODE_13', 6, np.str),
                         DataField('OTH_DIAG_CODE_14', 6, np.str),
                         DataField('OTH_DIAG_CODE_15', 6, np.str),
                         DataField('OTH_DIAG_CODE_16', 6, np.str),
                         DataField('OTH_DIAG_CODE_17', 6, np.str),
                         DataField('OTH_DIAG_CODE_18', 6, np.str),
                         DataField('OTH_DIAG_CODE_19', 6, np.str),
                         DataField('OTH_DIAG_CODE_20', 6, np.str),
                         DataField('OTH_DIAG_CODE_21', 6, np.str),
                         DataField('OTH_DIAG_CODE_22', 6, np.str),
                         DataField('OTH_DIAG_CODE_23', 6, np.str),
                         DataField('OTH_DIAG_CODE_24', 6, np.str),
                         DataField('PRINC_SURG_PROC_CODE', 7, np.str),
                         DataField('PRINC_SURG_PROC_DAY', 4, np.str),
                         DataField('PRINC_ICD9_CODE', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_1', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_1', 4, np.str),
                         DataField('OTH_ICD9_CODE_1', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_2', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_2', 4, np.str),
                         DataField('OTH_ICD9_CODE_2', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_3', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_3', 4, np.str),
                         DataField('OTH_ICD9_CODE_3', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_4', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_4', 4, np.str),
                         DataField('OTH_ICD9_CODE_4', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_5', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_5', 4, np.str),
                         DataField('OTH_ICD9_CODE_5', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_6', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_6', 4, np.str),
                         DataField('OTH_ICD9_CODE_6', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_7', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_7', 4, np.str),
                         DataField('OTH_ICD9_CODE_7', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_8', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_8', 4, np.str),
                         DataField('OTH_ICD9_CODE_8', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_9', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_9', 4, np.str),
                         DataField('OTH_ICD9_CODE_9', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_10', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_10', 4, np.str),
                         DataField('OTH_ICD9_CODE_10', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_11', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_11', 4, np.str),
                         DataField('OTH_ICD9_CODE_11', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_12', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_12', 4, np.str),
                         DataField('OTH_ICD9_CODE_12', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_13', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_13', 4, np.str),
                         DataField('OTH_ICD9_CODE_13', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_14', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_14', 4, np.str),
                         DataField('OTH_ICD9_CODE_14', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_15', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_15', 4, np.str),
                         DataField('OTH_ICD9_CODE_15', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_16', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_16', 4, np.str),
                         DataField('OTH_ICD9_CODE_16', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_17', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_17', 4, np.str),
                         DataField('OTH_ICD9_CODE_17', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_18', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_18', 4, np.str),
                         DataField('OTH_ICD9_CODE_18', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_19', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_19', 4, np.str),
                         DataField('OTH_ICD9_CODE_19', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_20', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_20', 4, np.str),
                         DataField('OTH_ICD9_CODE_20', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_21', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_21', 4, np.str),
                         DataField('OTH_ICD9_CODE_21', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_22', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_22', 4, np.str),
                         DataField('OTH_ICD9_CODE_22', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_23', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_23', 4, np.str),
                         DataField('OTH_ICD9_CODE_23', 5, np.str),
                         DataField('OTH_SURG_PROC_CODE_24', 7, np.str),
                         DataField('OTH_SURG_PROC_DAY_24', 4, np.str),
                         DataField('OTH_ICD9_CODE_24', 5, np.str),
                         DataField('E_CODE_1', 5, np.str),
                         DataField('E_CODE_2', 5, np.str),
                         DataField('E_CODE_3', 5, np.str),
                         DataField('E_CODE_4', 5, np.str),
                         DataField('E_CODE_5', 5, np.str),
                         DataField('E_CODE_6', 5, np.str),
                         DataField('E_CODE_7', 5, np.str),
                         DataField('E_CODE_8', 5, np.str),
                         DataField('E_CODE_9', 5, np.str),
                         DataField('E_CODE_10', 5, np.str),
                         DataField('CONDITION_CODE_1', 2, np.str),
                         DataField('CONDITION_CODE_2', 2, np.str),
                         DataField('CONDITION_CODE_3', 2, np.str),
                         DataField('CONDITION_CODE_4', 2, np.str),
                         DataField('CONDITION_CODE_5', 2, np.str),
                         DataField('CONDITION_CODE_6', 2, np.str),
                         DataField('CONDITION_CODE_7', 2, np.str),
                         DataField('CONDITION_CODE_8', 2, np.str),
                         DataField('OCCUR_CODE_1', 2, np.str),
                         DataField('OCCUR_DAY_1', 4, np.str),
                         DataField('OCCUR_CODE_2', 2, np.str),
                         DataField('OCCUR_DAY_2', 4, np.str),
                         DataField('OCCUR_CODE_3', 2, np.str),
                         DataField('OCCUR_DAY_3', 4, np.str),
                         DataField('OCCUR_CODE_4', 2, np.str),
                         DataField('OCCUR_DAY_4', 4, np.str),
                         DataField('OCCUR_CODE_5', 2, np.str),
                         DataField('OCCUR_DAY_5', 4, np.str),
                         DataField('OCCUR_CODE_6', 2, np.str),
                         DataField('OCCUR_DAY_6', 4, np.str),
                         DataField('OCCUR_CODE_7', 2, np.str),
                         DataField('OCCUR_DAY_7', 4, np.str),
                         DataField('OCCUR_CODE_8', 2, np.str),
                         DataField('OCCUR_DAY_8', 4, np.str),
                         DataField('OCCUR_CODE_9', 2, np.str),
                         DataField('OCCUR_DAY_9', 4, np.str),
                         DataField('OCCUR_CODE_10', 2, np.str),
                         DataField('OCCUR_DAY_10', 4, np.str),
                         DataField('OCCUR_CODE_11', 2, np.str),
                         DataField('OCCUR_DAY_11', 4, np.str),
                         DataField('OCCUR_CODE_12', 2, np.str),
                         DataField('OCCUR_DAY_12', 4, np.str),
                         DataField('OCCUR_SPAN_CODE_1', 2, np.str),
                         DataField('OCCUR_SPAN_FROM_1', 6, np.str),
                         DataField('OCCUR_SPAN_THRU_1', 6, np.str),
                         DataField('OCCUR_SPAN_CODE_2', 2, np.str),
                         DataField('OCCUR_SPAN_FROM_2', 6, np.str),
                         DataField('OCCUR_SPAN_THRU_2', 6, np.str),
                         DataField('OCCUR_SPAN_CODE_3', 2, np.str),
                         DataField('OCCUR_SPAN_FROM_3', 6, np.str),
                         DataField('OCCUR_SPAN_THRU_3', 6, np.str),
                         DataField('OCCUR_SPAN_CODE_4', 2, np.str),
                         DataField('OCCUR_SPAN_FROM_4', 6, np.str),
                         DataField('OCCUR_SPAN_THRU_4', 6, np.str),
                         DataField('VALUE_CODE_1', 2, np.str),
                         DataField('VALUE_AMOUNT_1', 9, np.str),
                         DataField('VALUE_CODE_2', 2, np.str),
                         DataField('VALUE_AMOUNT_2', 9, np.str),
                         DataField('VALUE_CODE_3', 2, np.str),
                         DataField('VALUE_AMOUNT_3', 9, np.str),
                         DataField('VALUE_CODE_4', 2, np.str),
                         DataField('VALUE_AMOUNT_4', 9, np.str),
                         DataField('VALUE_CODE_5', 2, np.str),
                         DataField('VALUE_AMOUNT_5', 9, np.str),
                         DataField('VALUE_CODE_6', 2, np.str),
                         DataField('VALUE_AMOUNT_6', 9, np.str),
                         DataField('VALUE_CODE_7', 2, np.str),
                         DataField('VALUE_AMOUNT_7', 9, np.str),
                         DataField('VALUE_CODE_8', 2, np.str),
                         DataField('VALUE_AMOUNT_8', 9, np.str),
                         DataField('VALUE_CODE_9', 2, np.str),
                         DataField('VALUE_AMOUNT_9', 9, np.str),
                         DataField('VALUE_CODE_10', 2, np.str),
                         DataField('VALUE_AMOUNT_10', 9, np.str),
                         DataField('VALUE_CODE_11', 2, np.str),
                         DataField('VALUE_AMOUNT_11', 9, np.str),
                         DataField('VALUE_CODE_12', 2, np.str),
                         DataField('VALUE_AMOUNT_12', 9, np.str),
                         DataField('CMS_MDC', 2, np.str),
                         DataField('APR_MDC', 2, np.str),
                         DataField('CMS_DRG', 2, np.str),
                         DataField('APR_DRG', 2, np.str),
                         DataField('RISK_MORTALITY', 1, np.str),
                         DataField('ILLNESS_SEVERITY', 1, np.str),
                         DataField('ATTENDING_PHYSICIAN_UNIF_ID', 10, np.str),
                         DataField('OPERATING_PHYSICIAN_UNIF_ID', 10, np.str),
                         DataField('CERT_STATUS', 1, np.str),
                         DataField('RECORD_ID', 12, np.str)]
    return base_data_fields

class DataField:
    """
    This class holds the three items defined in the documentation 
    for THCIC base data files.
    Name of field
    Length of field
    Type of field
    """
    def __init__(self, name, length, my_type):
        self.name = name
        self.length = length
        if my_type == np.str:
            new_type = '|S'
            new_type += str(length)
            self.type = new_type
        else:
            self.type = my_type



if __name__ == '__main__':
    base_data_fields = get_base_data_fields()   
    widths = [data_field.length for data_field in base_data_fields]
    header = [data_field.name for data_field in base_data_fields]
    types = [data_field.type for data_field in base_data_fields]
    rf = open('PUDF_base1q2007.txt','r')
    wf = open('mycsv.csv','w')
    writer = csv.writer(wf)
    #print [item for item in header]
    ndtypes = [(name,my_type) for name, my_type in zip(header,types)]
    print(ndtypes)
    writer.writerow(header)
    for row in rf:
        string_to_read = StringIO(row)
        my_data = np.genfromtxt(string_to_read, delimiter=widths,
                    dtype=ndtypes)
        restructured_data = [my_data[key] for key in header]
        #print restructured_data
        writer.writerow(restructured_data)

    

    rf.close()
    wf.close()





